# Generated by Django 5.1.2 on 2024-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
