# Generated by Django 5.1.2 on 2024-10-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="captaion",
            new_name="caption",
        ),
    ]
