# Generated by Django 5.1.2 on 2024-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_rename_captaion_post_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="viewers",
            field=models.IntegerField(default=0),
        ),
    ]
