# Generated by Django 5.1.2 on 2024-10-23 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_post_dislikes_post_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_bookmarked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
