# Generated by Django 5.1.2 on 2024-10-23 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_bookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True, related_name="post_bookmarked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="posts_disliked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="posts_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
