# Generated by Django 5.1.2 on 2025-03-31 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chattings", "0003_topic_room_host_room_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
