# Generated by Django 5.1.2 on 2025-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chicken_disease_detection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chickendiseasesample",
            old_name="conifidence_level",
            new_name="confidence_level",
        ),
    ]
